
DROP TABLE IF EXISTS UserProgress CASCADE;
DROP TABLE IF EXISTS Feedback CASCADE;
DROP TABLE IF EXISTS NutritionPlan CASCADE;
DROP TABLE IF EXISTS Exercise CASCADE;
DROP TABLE IF EXISTS Workout CASCADE;
DROP TABLE IF EXISTS TrainingProgram CASCADE;
